// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distImages
NumericMatrix distImages(arma::cube images, int verbosity);
RcppExport SEXP _curveDepth_distImages(SEXP imagesSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type images(imagesSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(distImages(images, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// distCurves
NumericMatrix distCurves(List curves, bool oneWay, int verbosity);
RcppExport SEXP _curveDepth_distCurves(SEXP curvesSEXP, SEXP oneWaySEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< bool >::type oneWay(oneWaySEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(distCurves(curves, oneWay, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// distCurvesAsymm
NumericMatrix distCurvesAsymm(List curvesRows, List curvesCols, bool oneWay, int verbosity);
RcppExport SEXP _curveDepth_distCurvesAsymm(SEXP curvesRowsSEXP, SEXP curvesColsSEXP, SEXP oneWaySEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type curvesRows(curvesRowsSEXP);
    Rcpp::traits::input_parameter< List >::type curvesCols(curvesColsSEXP);
    Rcpp::traits::input_parameter< bool >::type oneWay(oneWaySEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(distCurvesAsymm(curvesRows, curvesCols, oneWay, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// depthCurveTukey
NumericVector depthCurveTukey(List objects, List data, int nDirs, bool subs, double fracInt, double fracEst, double parConst1, double parConst2, int parMode, Nullable<List> subsamples, bool exactEst, double minMassObj, double minMassDat);
RcppExport SEXP _curveDepth_depthCurveTukey(SEXP objectsSEXP, SEXP dataSEXP, SEXP nDirsSEXP, SEXP subsSEXP, SEXP fracIntSEXP, SEXP fracEstSEXP, SEXP parConst1SEXP, SEXP parConst2SEXP, SEXP parModeSEXP, SEXP subsamplesSEXP, SEXP exactEstSEXP, SEXP minMassObjSEXP, SEXP minMassDatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nDirs(nDirsSEXP);
    Rcpp::traits::input_parameter< bool >::type subs(subsSEXP);
    Rcpp::traits::input_parameter< double >::type fracInt(fracIntSEXP);
    Rcpp::traits::input_parameter< double >::type fracEst(fracEstSEXP);
    Rcpp::traits::input_parameter< double >::type parConst1(parConst1SEXP);
    Rcpp::traits::input_parameter< double >::type parConst2(parConst2SEXP);
    Rcpp::traits::input_parameter< int >::type parMode(parModeSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type subsamples(subsamplesSEXP);
    Rcpp::traits::input_parameter< bool >::type exactEst(exactEstSEXP);
    Rcpp::traits::input_parameter< double >::type minMassObj(minMassObjSEXP);
    Rcpp::traits::input_parameter< double >::type minMassDat(minMassDatSEXP);
    rcpp_result_gen = Rcpp::wrap(depthCurveTukey(objects, data, nDirs, subs, fracInt, fracEst, parConst1, parConst2, parMode, subsamples, exactEst, minMassObj, minMassDat));
    return rcpp_result_gen;
END_RCPP
}
// curvesSubsample
List curvesSubsample(List curves, IntegerVector ptsPerCurve, bool randomPoints);
RcppExport SEXP _curveDepth_curvesSubsample(SEXP curvesSEXP, SEXP ptsPerCurveSEXP, SEXP randomPointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ptsPerCurve(ptsPerCurveSEXP);
    Rcpp::traits::input_parameter< bool >::type randomPoints(randomPointsSEXP);
    rcpp_result_gen = Rcpp::wrap(curvesSubsample(curves, ptsPerCurve, randomPoints));
    return rcpp_result_gen;
END_RCPP
}
// images2curves
List images2curves(arma::cube images);
RcppExport SEXP _curveDepth_images2curves(SEXP imagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type images(imagesSEXP);
    rcpp_result_gen = Rcpp::wrap(images2curves(images));
    return rcpp_result_gen;
END_RCPP
}
// depthCTukey
NumericVector depthCTukey(List objects, List data, int nDirs, bool subs, int m, double fracInt, double fracEst, bool exactEst, double minMassObj, double minMassDat, bool randObj, bool randDat);
RcppExport SEXP _curveDepth_depthCTukey(SEXP objectsSEXP, SEXP dataSEXP, SEXP nDirsSEXP, SEXP subsSEXP, SEXP mSEXP, SEXP fracIntSEXP, SEXP fracEstSEXP, SEXP exactEstSEXP, SEXP minMassObjSEXP, SEXP minMassDatSEXP, SEXP randObjSEXP, SEXP randDatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nDirs(nDirsSEXP);
    Rcpp::traits::input_parameter< bool >::type subs(subsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type fracInt(fracIntSEXP);
    Rcpp::traits::input_parameter< double >::type fracEst(fracEstSEXP);
    Rcpp::traits::input_parameter< bool >::type exactEst(exactEstSEXP);
    Rcpp::traits::input_parameter< double >::type minMassObj(minMassObjSEXP);
    Rcpp::traits::input_parameter< double >::type minMassDat(minMassDatSEXP);
    Rcpp::traits::input_parameter< bool >::type randObj(randObjSEXP);
    Rcpp::traits::input_parameter< bool >::type randDat(randDatSEXP);
    rcpp_result_gen = Rcpp::wrap(depthCTukey(objects, data, nDirs, subs, m, fracInt, fracEst, exactEst, minMassObj, minMassDat, randObj, randDat));
    return rcpp_result_gen;
END_RCPP
}
// setsSubsample
List setsSubsample(List sets, IntegerVector ptsPerSet, bool randomPoints);
RcppExport SEXP _curveDepth_setsSubsample(SEXP setsSEXP, SEXP ptsPerSetSEXP, SEXP randomPointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ptsPerSet(ptsPerSetSEXP);
    Rcpp::traits::input_parameter< bool >::type randomPoints(randomPointsSEXP);
    rcpp_result_gen = Rcpp::wrap(setsSubsample(sets, ptsPerSet, randomPoints));
    return rcpp_result_gen;
END_RCPP
}
// pointsSetsSubsample
List pointsSetsSubsample(List sets, IntegerVector ptsPerSet);
RcppExport SEXP _curveDepth_pointsSetsSubsample(SEXP setsSEXP, SEXP ptsPerSetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ptsPerSet(ptsPerSetSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsSetsSubsample(sets, ptsPerSet));
    return rcpp_result_gen;
END_RCPP
}
// depthSTukey
NumericVector depthSTukey(List objects, List data, String inputType, int nDirs, bool subs, int m, double fracInt, double fracEst, bool exactEst, double parConst1, double parConst2, int parMode, double minMassObj, double minMassDat, bool randObj, bool randDat);
RcppExport SEXP _curveDepth_depthSTukey(SEXP objectsSEXP, SEXP dataSEXP, SEXP inputTypeSEXP, SEXP nDirsSEXP, SEXP subsSEXP, SEXP mSEXP, SEXP fracIntSEXP, SEXP fracEstSEXP, SEXP exactEstSEXP, SEXP parConst1SEXP, SEXP parConst2SEXP, SEXP parModeSEXP, SEXP minMassObjSEXP, SEXP minMassDatSEXP, SEXP randObjSEXP, SEXP randDatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< String >::type inputType(inputTypeSEXP);
    Rcpp::traits::input_parameter< int >::type nDirs(nDirsSEXP);
    Rcpp::traits::input_parameter< bool >::type subs(subsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type fracInt(fracIntSEXP);
    Rcpp::traits::input_parameter< double >::type fracEst(fracEstSEXP);
    Rcpp::traits::input_parameter< bool >::type exactEst(exactEstSEXP);
    Rcpp::traits::input_parameter< double >::type parConst1(parConst1SEXP);
    Rcpp::traits::input_parameter< double >::type parConst2(parConst2SEXP);
    Rcpp::traits::input_parameter< int >::type parMode(parModeSEXP);
    Rcpp::traits::input_parameter< double >::type minMassObj(minMassObjSEXP);
    Rcpp::traits::input_parameter< double >::type minMassDat(minMassDatSEXP);
    Rcpp::traits::input_parameter< bool >::type randObj(randObjSEXP);
    Rcpp::traits::input_parameter< bool >::type randDat(randDatSEXP);
    rcpp_result_gen = Rcpp::wrap(depthSTukey(objects, data, inputType, nDirs, subs, m, fracInt, fracEst, exactEst, parConst1, parConst2, parMode, minMassObj, minMassDat, randObj, randDat));
    return rcpp_result_gen;
END_RCPP
}
// voxelize
List voxelize(List f, NumericVector from, NumericVector to, NumericVector by);
RcppExport SEXP _curveDepth_voxelize(SEXP fSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP bySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type by(bySEXP);
    rcpp_result_gen = Rcpp::wrap(voxelize(f, from, to, by));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_curveDepth_distImages", (DL_FUNC) &_curveDepth_distImages, 2},
    {"_curveDepth_distCurves", (DL_FUNC) &_curveDepth_distCurves, 3},
    {"_curveDepth_distCurvesAsymm", (DL_FUNC) &_curveDepth_distCurvesAsymm, 4},
    {"_curveDepth_depthCurveTukey", (DL_FUNC) &_curveDepth_depthCurveTukey, 13},
    {"_curveDepth_curvesSubsample", (DL_FUNC) &_curveDepth_curvesSubsample, 3},
    {"_curveDepth_images2curves", (DL_FUNC) &_curveDepth_images2curves, 1},
    {"_curveDepth_depthCTukey", (DL_FUNC) &_curveDepth_depthCTukey, 12},
    {"_curveDepth_setsSubsample", (DL_FUNC) &_curveDepth_setsSubsample, 3},
    {"_curveDepth_pointsSetsSubsample", (DL_FUNC) &_curveDepth_pointsSetsSubsample, 2},
    {"_curveDepth_depthSTukey", (DL_FUNC) &_curveDepth_depthSTukey, 16},
    {"_curveDepth_voxelize", (DL_FUNC) &_curveDepth_voxelize, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_curveDepth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
